# fly.toml app configuration file generated for birds-of-play on 2023-06-08T15:21:43-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "birds-of-play"
primary_region = "iad"
console_command = "/code/manage.py shell"

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
